TITLE = "Genetic Level Checker"
SCR_W = 0
SCR_H = 0
FPS = 60

GRAVITY = 0.5
HUMAN_CONTROL = False
TILE_SIZE = 30
LEVEL_NAME = 'level.csv'
DEFAULT_BRAIN_SIZE = 500
MUTATION_RATE = 0.03
ELITISM_RATIO = 3
POPULATION_SIZE = 100

GENERATIONS_WITHOUT_RENDER = 10000
SWAP_FITNESS = 20

PLAYER_SPAWN_X = 0
PLAYER_SPAWN_Y = 0

BEST_X = 0
BEST_Y = 0

# data globals
goal = None
