TITLE = "Genetic Level Checker"
SCR_W = 0
SCR_H = 0
FPS = 120

GRAVITY = 0.5
HUMAN_CONTROL = False
TILE_SIZE = 30
LEVEL_NAME = 'level.csv'
DEFAULT_BRAIN_SIZE = 400
MUTATION_RATE = 0.01
ELITISM_RATIO = 2
POPULATION_SIZE = 100

GENERATIONS_WITHOUT_RENDER = 100

PLAYER_SPAWN_X = 0
PLAYER_SPAWN_Y = 0

# data globals
goal = None